// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using recode_work_api.Models;

#nullable disable

namespace recode_work_api.Migrations
{
    [DbContext(typeof(TripDbContext))]
    partial class TripDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("recode_work_api.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Boarding")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("varchar(5000)");

                    b.Property<string>("Destiny")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<double>("Promotion")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Boarding = "Rio de janeiro/Brasil",
                            Date = "2023-10-5",
                            Description = "Viajem internacional",
                            Destiny = "Berlim/Alemanha",
                            Price = 150.0,
                            Promotion = 0.80000000000000004
                        },
                        new
                        {
                            Id = 2,
                            Boarding = "São Paulo/Brasil",
                            Date = "2023-01-12",
                            Description = "Viajem internacional",
                            Destiny = "Tóquio/Japão",
                            Price = 500.0,
                            Promotion = 0.84999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Boarding = "Rio de janeiro/Brazil",
                            Date = "2023-12-7",
                            Description = "Viajem internacional",
                            Destiny = "Berlim/Alemanha",
                            Price = 100.0,
                            Promotion = 1.0
                        },
                        new
                        {
                            Id = 4,
                            Boarding = "Rio branco/Brasil",
                            Date = "2023-02-30",
                            Description = "Viajem internacional",
                            Destiny = "Porto/Portugal",
                            Price = 150.0,
                            Promotion = 0.75
                        },
                        new
                        {
                            Id = 5,
                            Boarding = "Florianopólis/Brasil",
                            Date = "2023-08-10",
                            Description = "Viajem internacional",
                            Destiny = "Nova Yorque/Estados Unidos",
                            Price = 850.0,
                            Promotion = 0.94999999999999996
                        },
                        new
                        {
                            Id = 6,
                            Boarding = "Rio de janeiro/Brazil",
                            Date = "2023-02-20",
                            Description = "Viajem internacional",
                            Destiny = "Buenos Ares/Argentina",
                            Price = 100.5,
                            Promotion = 0.84999999999999998
                        },
                        new
                        {
                            Id = 7,
                            Boarding = "Gramados/Brasil",
                            Date = "2023-04-25",
                            Description = "Viajem internacional",
                            Destiny = "Madri/Espanha",
                            Price = 650.0,
                            Promotion = 0.75
                        },
                        new
                        {
                            Id = 8,
                            Boarding = "Rio de janeiro/Brazil",
                            Date = "2023-07-5",
                            Description = "Viajem internacional",
                            Destiny = "Berlim/Alemanha",
                            Price = 100.0,
                            Promotion = 0.80000000000000004
                        },
                        new
                        {
                            Id = 9,
                            Boarding = "Salvador/Brasil",
                            Date = "2023-08-12",
                            Description = "Viajem internacional",
                            Destiny = "Capital da Angola/Angola",
                            Price = 250.0,
                            Promotion = 0.90000000000000002
                        },
                        new
                        {
                            Id = 10,
                            Boarding = "Vitória/Brazil",
                            Date = "2023-12-15",
                            Description = "Viajem internacional",
                            Destiny = "Paris/França",
                            Price = 725.0,
                            Promotion = 0.84999999999999998
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
